services:
  listener:
    build:
      context: ./kotonoha
    env_file:
      - ./kotonoha/.env
    ports:
      - "8081:8081"
  voicevox:
    image: "voicevox/voicevox_engine"
    ports:
      - "50021:50021"
